<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.11">
  <POU Name="MAIN" Id="{fc58933e-47a6-4fd8-a367-fd7f6c32aed5}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	bZmienna1: BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="1" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>